# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PACoin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PACoin.proto',
  package='PACoin',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cPACoin.proto\x12\x06PACoin\"\x1b\n\x0bPingRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\"\'\n\tPingReply\x12\x1a\n\x03ret\x18\x01 \x01(\x0e\x32\r.PACoin.ERRNO\"\x1f\n\x10PullPeersRequest\x12\x0b\n\x03num\x18\x01 \x01(\x04\";\n\x0ePullPeersReply\x12\x1a\n\x03ret\x18\x01 \x01(\x0e\x32\r.PACoin.ERRNO\x12\r\n\x05hosts\x18\x02 \x03(\t\"\x1b\n\x0bTransaction\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"4\n\x0fSendTxnsRequest\x12!\n\x04txns\x18\x01 \x03(\x0b\x32\x13.PACoin.Transaction\"+\n\rSendTxnsReply\x12\x1a\n\x03ret\x18\x01 \x01(\x0e\x32\r.PACoin.ERRNO\"\x15\n\x05\x42lock\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"2\n\x11SendBlocksRequest\x12\x1d\n\x06\x62locks\x18\x01 \x03(\x0b\x32\r.PACoin.Block\"-\n\x0fSendBlocksReply\x12\x1a\n\x03ret\x18\x01 \x01(\x0e\x32\r.PACoin.ERRNO\".\n\x11PullBlocksRequest\x12\x0c\n\x04\x62\x61se\x18\x01 \x01(\x04\x12\x0b\n\x03num\x18\x02 \x01(\x04\"L\n\x0fPullBlocksReply\x12\x1a\n\x03ret\x18\x01 \x01(\x0e\x32\r.PACoin.ERRNO\x12\x1d\n\x06\x62locks\x18\x02 \x03(\x0b\x32\r.PACoin.Block\"!\n\x11SyncStatusRequest\x12\x0c\n\x04\x63urr\x18\x01 \x01(\x04\";\n\x0fSyncStatusReply\x12\x1a\n\x03ret\x18\x01 \x01(\x0e\x32\r.PACoin.ERRNO\x12\x0c\n\x04\x63urr\x18\x02 \x01(\x04*\x1f\n\x05\x45RRNO\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32\x81\x01\n\x0cP2PDiscovery\x12\x30\n\x04ping\x12\x13.PACoin.PingRequest\x1a\x11.PACoin.PingReply\"\x00\x12?\n\tpullPeers\x12\x18.PACoin.PullPeersRequest\x1a\x16.PACoin.PullPeersReply\"\x00\x32S\n\x13TransactionTransfer\x12<\n\x08sendTxns\x12\x17.PACoin.SendTxnsRequest\x1a\x15.PACoin.SendTxnsReply\"\x00\x32\xdb\x01\n\rBlockTransfer\x12\x42\n\nsendBlocks\x12\x19.PACoin.SendBlocksRequest\x1a\x17.PACoin.SendBlocksReply\"\x00\x12\x42\n\npullBlocks\x12\x19.PACoin.PullBlocksRequest\x1a\x17.PACoin.PullBlocksReply\"\x00\x12\x42\n\nsyncStatus\x12\x19.PACoin.SyncStatusRequest\x1a\x17.PACoin.SyncStatusReply\"\x00\x62\x06proto3')
)

_ERRNO = _descriptor.EnumDescriptor(
  name='ERRNO',
  full_name='PACoin.ERRNO',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=660,
  serialized_end=691,
)
_sym_db.RegisterEnumDescriptor(_ERRNO)

ERRNO = enum_type_wrapper.EnumTypeWrapper(_ERRNO)
SUCCESS = 0
ERROR = 1



_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='PACoin.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='PACoin.PingRequest.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=51,
)


_PINGREPLY = _descriptor.Descriptor(
  name='PingReply',
  full_name='PACoin.PingReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='PACoin.PingReply.ret', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=92,
)


_PULLPEERSREQUEST = _descriptor.Descriptor(
  name='PullPeersRequest',
  full_name='PACoin.PullPeersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='PACoin.PullPeersRequest.num', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=125,
)


_PULLPEERSREPLY = _descriptor.Descriptor(
  name='PullPeersReply',
  full_name='PACoin.PullPeersReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='PACoin.PullPeersReply.ret', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hosts', full_name='PACoin.PullPeersReply.hosts', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=186,
)


_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='PACoin.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='PACoin.Transaction.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=215,
)


_SENDTXNSREQUEST = _descriptor.Descriptor(
  name='SendTxnsRequest',
  full_name='PACoin.SendTxnsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txns', full_name='PACoin.SendTxnsRequest.txns', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=269,
)


_SENDTXNSREPLY = _descriptor.Descriptor(
  name='SendTxnsReply',
  full_name='PACoin.SendTxnsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='PACoin.SendTxnsReply.ret', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=314,
)


_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='PACoin.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='PACoin.Block.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=337,
)


_SENDBLOCKSREQUEST = _descriptor.Descriptor(
  name='SendBlocksRequest',
  full_name='PACoin.SendBlocksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blocks', full_name='PACoin.SendBlocksRequest.blocks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=389,
)


_SENDBLOCKSREPLY = _descriptor.Descriptor(
  name='SendBlocksReply',
  full_name='PACoin.SendBlocksReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='PACoin.SendBlocksReply.ret', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=436,
)


_PULLBLOCKSREQUEST = _descriptor.Descriptor(
  name='PullBlocksRequest',
  full_name='PACoin.PullBlocksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='PACoin.PullBlocksRequest.base', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='PACoin.PullBlocksRequest.num', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=484,
)


_PULLBLOCKSREPLY = _descriptor.Descriptor(
  name='PullBlocksReply',
  full_name='PACoin.PullBlocksReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='PACoin.PullBlocksReply.ret', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blocks', full_name='PACoin.PullBlocksReply.blocks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=562,
)


_SYNCSTATUSREQUEST = _descriptor.Descriptor(
  name='SyncStatusRequest',
  full_name='PACoin.SyncStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='curr', full_name='PACoin.SyncStatusRequest.curr', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=564,
  serialized_end=597,
)


_SYNCSTATUSREPLY = _descriptor.Descriptor(
  name='SyncStatusReply',
  full_name='PACoin.SyncStatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='PACoin.SyncStatusReply.ret', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='curr', full_name='PACoin.SyncStatusReply.curr', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=599,
  serialized_end=658,
)

_PINGREPLY.fields_by_name['ret'].enum_type = _ERRNO
_PULLPEERSREPLY.fields_by_name['ret'].enum_type = _ERRNO
_SENDTXNSREQUEST.fields_by_name['txns'].message_type = _TRANSACTION
_SENDTXNSREPLY.fields_by_name['ret'].enum_type = _ERRNO
_SENDBLOCKSREQUEST.fields_by_name['blocks'].message_type = _BLOCK
_SENDBLOCKSREPLY.fields_by_name['ret'].enum_type = _ERRNO
_PULLBLOCKSREPLY.fields_by_name['ret'].enum_type = _ERRNO
_PULLBLOCKSREPLY.fields_by_name['blocks'].message_type = _BLOCK
_SYNCSTATUSREPLY.fields_by_name['ret'].enum_type = _ERRNO
DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingReply'] = _PINGREPLY
DESCRIPTOR.message_types_by_name['PullPeersRequest'] = _PULLPEERSREQUEST
DESCRIPTOR.message_types_by_name['PullPeersReply'] = _PULLPEERSREPLY
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
DESCRIPTOR.message_types_by_name['SendTxnsRequest'] = _SENDTXNSREQUEST
DESCRIPTOR.message_types_by_name['SendTxnsReply'] = _SENDTXNSREPLY
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['SendBlocksRequest'] = _SENDBLOCKSREQUEST
DESCRIPTOR.message_types_by_name['SendBlocksReply'] = _SENDBLOCKSREPLY
DESCRIPTOR.message_types_by_name['PullBlocksRequest'] = _PULLBLOCKSREQUEST
DESCRIPTOR.message_types_by_name['PullBlocksReply'] = _PULLBLOCKSREPLY
DESCRIPTOR.message_types_by_name['SyncStatusRequest'] = _SYNCSTATUSREQUEST
DESCRIPTOR.message_types_by_name['SyncStatusReply'] = _SYNCSTATUSREPLY
DESCRIPTOR.enum_types_by_name['ERRNO'] = _ERRNO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), dict(
  DESCRIPTOR = _PINGREQUEST,
  __module__ = 'PACoin_pb2'
  # @@protoc_insertion_point(class_scope:PACoin.PingRequest)
  ))
_sym_db.RegisterMessage(PingRequest)

PingReply = _reflection.GeneratedProtocolMessageType('PingReply', (_message.Message,), dict(
  DESCRIPTOR = _PINGREPLY,
  __module__ = 'PACoin_pb2'
  # @@protoc_insertion_point(class_scope:PACoin.PingReply)
  ))
_sym_db.RegisterMessage(PingReply)

PullPeersRequest = _reflection.GeneratedProtocolMessageType('PullPeersRequest', (_message.Message,), dict(
  DESCRIPTOR = _PULLPEERSREQUEST,
  __module__ = 'PACoin_pb2'
  # @@protoc_insertion_point(class_scope:PACoin.PullPeersRequest)
  ))
_sym_db.RegisterMessage(PullPeersRequest)

PullPeersReply = _reflection.GeneratedProtocolMessageType('PullPeersReply', (_message.Message,), dict(
  DESCRIPTOR = _PULLPEERSREPLY,
  __module__ = 'PACoin_pb2'
  # @@protoc_insertion_point(class_scope:PACoin.PullPeersReply)
  ))
_sym_db.RegisterMessage(PullPeersReply)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTION,
  __module__ = 'PACoin_pb2'
  # @@protoc_insertion_point(class_scope:PACoin.Transaction)
  ))
_sym_db.RegisterMessage(Transaction)

SendTxnsRequest = _reflection.GeneratedProtocolMessageType('SendTxnsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENDTXNSREQUEST,
  __module__ = 'PACoin_pb2'
  # @@protoc_insertion_point(class_scope:PACoin.SendTxnsRequest)
  ))
_sym_db.RegisterMessage(SendTxnsRequest)

SendTxnsReply = _reflection.GeneratedProtocolMessageType('SendTxnsReply', (_message.Message,), dict(
  DESCRIPTOR = _SENDTXNSREPLY,
  __module__ = 'PACoin_pb2'
  # @@protoc_insertion_point(class_scope:PACoin.SendTxnsReply)
  ))
_sym_db.RegisterMessage(SendTxnsReply)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
  DESCRIPTOR = _BLOCK,
  __module__ = 'PACoin_pb2'
  # @@protoc_insertion_point(class_scope:PACoin.Block)
  ))
_sym_db.RegisterMessage(Block)

SendBlocksRequest = _reflection.GeneratedProtocolMessageType('SendBlocksRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENDBLOCKSREQUEST,
  __module__ = 'PACoin_pb2'
  # @@protoc_insertion_point(class_scope:PACoin.SendBlocksRequest)
  ))
_sym_db.RegisterMessage(SendBlocksRequest)

SendBlocksReply = _reflection.GeneratedProtocolMessageType('SendBlocksReply', (_message.Message,), dict(
  DESCRIPTOR = _SENDBLOCKSREPLY,
  __module__ = 'PACoin_pb2'
  # @@protoc_insertion_point(class_scope:PACoin.SendBlocksReply)
  ))
_sym_db.RegisterMessage(SendBlocksReply)

PullBlocksRequest = _reflection.GeneratedProtocolMessageType('PullBlocksRequest', (_message.Message,), dict(
  DESCRIPTOR = _PULLBLOCKSREQUEST,
  __module__ = 'PACoin_pb2'
  # @@protoc_insertion_point(class_scope:PACoin.PullBlocksRequest)
  ))
_sym_db.RegisterMessage(PullBlocksRequest)

PullBlocksReply = _reflection.GeneratedProtocolMessageType('PullBlocksReply', (_message.Message,), dict(
  DESCRIPTOR = _PULLBLOCKSREPLY,
  __module__ = 'PACoin_pb2'
  # @@protoc_insertion_point(class_scope:PACoin.PullBlocksReply)
  ))
_sym_db.RegisterMessage(PullBlocksReply)

SyncStatusRequest = _reflection.GeneratedProtocolMessageType('SyncStatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _SYNCSTATUSREQUEST,
  __module__ = 'PACoin_pb2'
  # @@protoc_insertion_point(class_scope:PACoin.SyncStatusRequest)
  ))
_sym_db.RegisterMessage(SyncStatusRequest)

SyncStatusReply = _reflection.GeneratedProtocolMessageType('SyncStatusReply', (_message.Message,), dict(
  DESCRIPTOR = _SYNCSTATUSREPLY,
  __module__ = 'PACoin_pb2'
  # @@protoc_insertion_point(class_scope:PACoin.SyncStatusReply)
  ))
_sym_db.RegisterMessage(SyncStatusReply)



_P2PDISCOVERY = _descriptor.ServiceDescriptor(
  name='P2PDiscovery',
  full_name='PACoin.P2PDiscovery',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=694,
  serialized_end=823,
  methods=[
  _descriptor.MethodDescriptor(
    name='ping',
    full_name='PACoin.P2PDiscovery.ping',
    index=0,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PINGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='pullPeers',
    full_name='PACoin.P2PDiscovery.pullPeers',
    index=1,
    containing_service=None,
    input_type=_PULLPEERSREQUEST,
    output_type=_PULLPEERSREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_P2PDISCOVERY)

DESCRIPTOR.services_by_name['P2PDiscovery'] = _P2PDISCOVERY


_TRANSACTIONTRANSFER = _descriptor.ServiceDescriptor(
  name='TransactionTransfer',
  full_name='PACoin.TransactionTransfer',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=825,
  serialized_end=908,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendTxns',
    full_name='PACoin.TransactionTransfer.sendTxns',
    index=0,
    containing_service=None,
    input_type=_SENDTXNSREQUEST,
    output_type=_SENDTXNSREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSACTIONTRANSFER)

DESCRIPTOR.services_by_name['TransactionTransfer'] = _TRANSACTIONTRANSFER


_BLOCKTRANSFER = _descriptor.ServiceDescriptor(
  name='BlockTransfer',
  full_name='PACoin.BlockTransfer',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=911,
  serialized_end=1130,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendBlocks',
    full_name='PACoin.BlockTransfer.sendBlocks',
    index=0,
    containing_service=None,
    input_type=_SENDBLOCKSREQUEST,
    output_type=_SENDBLOCKSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='pullBlocks',
    full_name='PACoin.BlockTransfer.pullBlocks',
    index=1,
    containing_service=None,
    input_type=_PULLBLOCKSREQUEST,
    output_type=_PULLBLOCKSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='syncStatus',
    full_name='PACoin.BlockTransfer.syncStatus',
    index=2,
    containing_service=None,
    input_type=_SYNCSTATUSREQUEST,
    output_type=_SYNCSTATUSREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOCKTRANSFER)

DESCRIPTOR.services_by_name['BlockTransfer'] = _BLOCKTRANSFER

# @@protoc_insertion_point(module_scope)
